receivers:
  awsxray:
    endpoint: 0.0.0.0:2000

exporters:
  awsxray: {}
  debug:
    verbosity: detailed

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [awsxray]
      processors: [batch]
      exporters: [awsxray, debug]

