apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-app-template
  title: React Application
  description: A modern React application with TypeScript, Vite, and best practices for frontend development
  tags:
    - react
    - typescript
    - vite
    - frontend
    - spa
    - component
    - ui
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: platform-team
  type: component
  lifecycle: production

  parameters:
    - title: Project Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Project Name
          type: string
          description: Unique name of the React application (use lowercase letters, numbers, and hyphens only)
          pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
          ui:autofocus: true
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Brief description of the React application
          ui:widget: textarea
          ui:options:
            rows: 3
        owner:
          title: Owner
          type: string
          description: Owner of the component (user or team)
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - User
              - Group
        reactVersion:
          title: React Version
          type: string
          description: React version to use
          enum: ['18.x', '17.x']
          default: '18.x'
        useTypeScript:
          title: Use TypeScript
          type: boolean
          description: Whether to use TypeScript for type safety
          default: true
        useRouter:
          title: Include Router
          type: boolean
          description: Include React Router for navigation
          default: true
        useStateManagement:
          title: State Management
          type: string
          description: State management library to use
          enum: ['none', 'zustand', 'redux-toolkit', 'context-api']
          default: 'none'
        uiFramework:
          title: UI Framework
          type: string
          description: UI component library to use
          enum: ['none', 'ant-design', 'material-ui', 'chakra-ui', 'tailwind']
          default: 'none'

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Where should the code be stored?
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com

    - title: Build & Deployment
      properties:
        enableCI:
          title: Enable CI/CD
          type: boolean
          description: Enable continuous integration and deployment
          default: true
        deploymentTarget:
          title: Deployment Target
          type: string
          description: Target deployment platform
          enum: ['vercel', 'netlify', 'aws-s3', 'none']
          default: 'vercel'

  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          component_id: ${{ parameters.name }}
          destination: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          __APP_NAME__: ${{ parameters.name }}
          reactVersion: ${{ parameters.reactVersion }}
          useTypeScript: ${{ parameters.useTypeScript }}
          useRouter: ${{ parameters.useRouter }}
          useStateManagement: ${{ parameters.useStateManagement }}
          uiFramework: ${{ parameters.uiFramework }}
          enableCI: ${{ parameters.enableCI }}
          deploymentTarget: ${{ parameters.deploymentTarget }}

    - id: publish
      name: Publish to Repository
      action: publish:github
      input:
        allowedHosts:
          - github.com
          - gitlab.com
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        gitCommitMessage: 'Initial commit: Created from React Application Template'
        gitAuthorName: 'Backstage Scaffolder'
        gitAuthorEmail: 'scaffolder@backstage.io'

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    - id: notify
      name: Notify User
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - ${{ parameters.owner }}
        title: 'React Application Created Successfully!'
        info: 'Your React application "${{ parameters.name }}" has been created and is ready for development.'
        severity: success

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
        icon: source
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: View TechDocs
        icon: docs
        url: ${{ steps.publish.output.remoteUrl }}/blob/main/docs/index.md
      - title: Storybook
        url: ${{ steps.publish.output.remoteUrl }}/blob/main/.storybook/main.js
        icon: book