apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.description }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - ${{ values.framework }}
    - api
    - backend
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}

