apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-new-project
  description: A new Backstage application created using the latest best practices.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: experimental

